In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [46]:
df = pd.read_csv("Web_Series.csv")
df.head()

,Series Title,Year Released,Content Rating,IMDB Rating,R Rating,Genre,Description,No of Seasons,Streaming Platform
0,Breaking Bad,2008,18+,9.5,100,"Crime,Drama","When Walter White, a New Mexico chemistry teac...",5Seasons,Netflix
1,Game of Thrones,2011,18+,9.3,99,"Action & Adventure,Drama",Seven noble families fight for control of the ...,8Seasons,"HBO MAX,HBO"
2,Rick and Morty,2013,18+,9.2,97,"Animation,Comedy",Rick is a mentally-unbalanced but scientifical...,4Seasons,"Free Services,HBO MAX,Hulu"
3,Stranger Things,2016,16+,8.8,96,"Drama,Fantasy","When a young boy vanishes, a small town uncove...",3Seasons,Netflix
4,The Boys,2019,18+,8.7,95,"Action & Adventure,Comedy",A group of vigilantes known informally as “The...,2Seasons,Prime Video

In [47]:
df.dtypes

Series Title           object
Year Released           int64
Content Rating         object
IMDB Rating           float64
R Rating                int64
Genre                  object
Description            object
No of Seasons          object
Streaming Platform     object
dtype: object

In [48]:

df = df.join(pd.get_dummies(df["Streaming Platform"],dtype =int ))
df.head(1)

,Series Title,Year Released,Content Rating,IMDB Rating,R Rating,Genre,Description,No of Seasons,Streaming Platform,-1,...,"VH1,BET+",Viceland,"Viceland,fuboTV","Viceland,fuboTV,Hoopla",YouTube Premium,"YouTube Premium,Hoopla",fuboTV,"fuboTV,BET+","fuboTV,Hoopla","fuboTV,Peacock Premium"
0,Breaking Bad,2008,18+,9.5,100,"Crime,Drama","When Walter White, a New Mexico chemistry teac...",5Seasons,Netflix,0,...,0,0,0,0,0,0,0,0,0,0

In [49]:
df.columns

Index(['Series Title', 'Year Released', 'Content Rating', 'IMDB Rating',
       'R Rating', 'Genre', 'Description', 'No of Seasons',
       'Streaming Platform', '-1',
       ...
       'VH1,BET+', 'Viceland', 'Viceland,fuboTV', 'Viceland,fuboTV,Hoopla',
       'YouTube Premium', 'YouTube Premium,Hoopla', 'fuboTV', 'fuboTV,BET+',
       'fuboTV,Hoopla', 'fuboTV,Peacock Premium'],
      dtype='object', length=539)

In [50]:
x = df[df.columns.drop(['Series Title', 'Content Rating', 'IMDB Rating', 'Genre', 'Description', 'No of Seasons','Streaming Platform'])]

In [51]:
from sklearn.preprocessing import StandardScaler
x = StandardScaler().fit_transform(x)

In [ ]:
from sklearn.cluster import KMeans
modelkm = KMeans(n_clusters=3)
modelkm.fit(x)

array([1, 1, 1, ..., 1, 1, 0], shape=(12353,), dtype=int32)

In [53]:
modelkm.labels_

array([1, 1, 1, ..., 1, 1, 0], shape=(12353,), dtype=int32)