
!pip install arff-csv-converter

In [26]:
import pandas as pd
import numpy as np

In [27]:
from arff_csv import arff_to_csv
df = arff_to_csv("data_plant.arff", "data.csv")
df = pd.DataFrame(df)
df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V56,V57,V58,V59,V60,V61,V62,V63,V64,Class
0,0.000579,0.000609,0.000551,0.000554,0.000603,0.000614,0.000611,0.000611,0.000611,0.000594,...,0.000533,0.000555,0.000565,0.000581,0.000597,0.000625,0.000624,0.000617,0.000614,13
1,0.000630,0.000661,0.000719,0.000651,0.000643,0.000640,0.000646,0.000624,0.000584,0.000546,...,0.000520,0.000533,0.000564,0.000596,0.000623,0.000642,0.000661,0.000671,0.000667,13
2,0.000616,0.000615,0.000606,0.000568,0.000558,0.000552,0.000551,0.000552,0.000531,0.000530,...,0.000590,0.000589,0.000566,0.000575,0.000618,0.000543,0.000592,0.000607,0.000602,13
3,0.000613,0.000569,0.000564,0.000607,0.000643,0.000647,0.000663,0.000658,0.000635,0.000600,...,0.000536,0.000549,0.000542,0.000566,0.000592,0.000601,0.000609,0.000614,0.000603,13
4,0.000599,0.000552,0.000558,0.000569,0.000616,0.000639,0.000631,0.000634,0.000639,0.000596,...,0.000543,0.000557,0.000562,0.000558,0.000591,0.000608,0.000613,0.000610,0.000594,13

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 65 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   V1      1600 non-null   float64
 1   V2      1600 non-null   float64
 2   V3      1600 non-null   float64
 3   V4      1600 non-null   float64
 4   V5      1600 non-null   float64
 5   V6      1600 non-null   float64
 6   V7      1600 non-null   float64
 7   V8      1600 non-null   float64
 8   V9      1600 non-null   float64
 9   V10     1600 non-null   float64
 10  V11     1600 non-null   float64
 11  V12     1600 non-null   float64
 12  V13     1600 non-null   float64
 13  V14     1600 non-null   float64
 14  V15     1600 non-null   float64
 15  V16     1600 non-null   float64
 16  V17     1600 non-null   float64
 17  V18     1600 non-null   float64
 18  V19     1600 non-null   float64
 19  V20     1600 non-null   float64
 20  V21     1600 non-null   float64
 21  V22     1600 non-null   float64
 22  V23     1600 non-null   float64
 23  V24     1600 non-null   float64
 24  V25     1600 non-null   float64
 25  V26     1600 non-null   float64
 26  V27     1600 non-null   float64
 27  V28     1600 non-null   float64
 28  V29     1600 non-null   float64
 29  V30     1600 non-null   float64
 30  V31     1600 non-null   float64
 31  V32     1600 non-null   float64
 32  V33     1600 non-null   float64
 33  V34     1600 non-null   float64
 34  V35     1600 non-null   float64
 35  V36     1600 non-null   float64
 36  V37     1600 non-null   float64
 37  V38     1600 non-null   float64
 38  V39     1600 non-null   float64
 39  V40     1600 non-null   float64
 40  V41     1600 non-null   float64
 41  V42     1600 non-null   float64
 42  V43     1600 non-null   float64
 43  V44     1600 non-null   float64
 44  V45     1600 non-null   float64
 45  V46     1600 non-null   float64
 46  V47     1600 non-null   float64
 47  V48     1600 non-null   float64
 48  V49     1600 non-null   float64
 49  V50     1600 non-null   float64
 50  V51     1600 non-null   float64
 51  V52     1600 non-null   float64
 52  V53     1600 non-null   float64
 53  V54     1600 non-null   float64
 54  V55     1600 non-null   float64
 55  V56     1600 non-null   float64
 56  V57     1600 non-null   float64
 57  V58     1600 non-null   float64
 58  V59     1600 non-null   float64
 59  V60     1600 non-null   float64
 60  V61     1600 non-null   float64
 61  V62     1600 non-null   float64
 62  V63     1600 non-null   float64
 63  V64     1600 non-null   float64
 64  Class   1600 non-null   category
dtypes: category(1), float64(64)
memory usage: 806.5 KB

In [29]:
x = df.drop(columns = "Class")
y = df["Class"]

In [30]:
from sklearn.preprocessing import StandardScaler

In [31]:
from sklearn.model_selection import train_test_split
xtrain , xtest , ytrain , ytest = train_test_split(x,y,test_size=0.2,random_state= 85)

In [32]:
from lazypredict.Supervised import LazyClassifier
clf = LazyClassifier()
models ,gout= clf.fit(xtrain,xtest,ytrain,ytest)
models

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Precision,Recall,Time Taken
Model,,,,,,,
ExtraTreesClassifier,0.659375,0.670422,None,0.653388,0.719029,0.659375,0.688658
NuSVC,0.656250,0.662003,None,0.644515,0.719929,0.656250,0.809151
LogisticRegression,0.634375,0.645925,None,0.623887,0.704330,0.634375,1.652772
LabelPropagation,0.615625,0.630290,None,0.601205,0.673534,0.615625,0.189402
LabelSpreading,0.615625,0.630290,None,0.601205,0.673534,0.615625,1.064416
RandomForestClassifier,0.606250,0.612347,None,0.592375,0.653795,0.606250,1.964620
KNeighborsClassifier,0.543750,0.568066,None,0.527433,0.581941,0.543750,0.148085
BaggingClassifier,0.525000,0.541163,None,0.506986,0.555342,0.525000,1.426740
LinearSVC,0.509375,0.512592,None,0.486922,0.523482,0.509375,1.007802
LinearDiscriminantAnalysis,0.506250,0.503216,None,0.486925,0.553553,0.506250,0.151757
GaussianNB,0.493750,0.502209,None,0.481711,0.533827,0.493750,0.088448
NearestCentroid,0.465625,0.484094,None,0.441562,0.481533,0.465625,0.190713
CalibratedClassifierCV,0.468750,0.478891,None,0.429281,0.487555,0.468750,4.905388
SVC,0.384375,0.460015,None,0.339440,0.392708,0.384375,0.695150
DecisionTreeClassifier,0.425000,0.411046,None,0.412338,0.460484,0.425000,0.242234
ExtraTreeClassifier,0.365625,0.357192,None,0.378038,0.434844,0.365625,0.049407
RidgeClassifier,0.278125,0.305596,None,0.216068,0.268703,0.278125,0.054520
RidgeClassifierCV,0.250000,0.275945,None,0.169703,0.171544,0.250000,0.134097
PassiveAggressiveClassifier,0.200000,0.191924,None,0.186124,0.222841,0.200000,0.342395
BernoulliNB,0.159375,0.170275,None,0.148166,0.193873,0.159375,0.084255
Perceptron,0.140625,0.141507,None,0.132410,0.159603,0.140625,0.250178
SGDClassifier,0.118750,0.137457,None,0.116058,0.144827,0.118750,0.679073
QuadraticDiscriminantAnalysis,0.059375,0.057683,None,0.061291,0.088333,0.059375,0.089914
AdaBoostClassifier,0.040625,0.030928,None,0.003625,0.001910,0.040625,1.070608
DummyClassifier,0.000000,0.000000,None,0.000000,0.000000,0.000000,0.042761

In [33]:
hot = list(df.columns)
hot = hot[:-1:]
print(hot)

['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51', 'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61', 'V62', 'V63', 'V64']

In [34]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer

cl = make_column_transformer((StandardScaler(),hot),remainder="passthrough")
pipi = make_pipeline(cl,ExtraTreesClassifier())

In [35]:
pipi.fit(xtrain,ytrain)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['V1', 'V2', 'V3', 'V4', 'V5',
                                                   'V6', 'V7', 'V8', 'V9',
                                                   'V10', 'V11', 'V12', 'V13',
                                                   'V14', 'V15', 'V16', 'V17',
                                                   'V18', 'V19', 'V20', 'V21',
                                                   'V22', 'V23', 'V24', 'V25',
                                                   'V26', 'V27', 'V28', 'V29',
                                                   'V30', ...])])),
                ('extratreesclassifier', ExtraTreesClassifier())])

In [36]:
yhat = pipi.predict(xtest)
from sklearn.metrics import classification_report as cr 
print(cr(ytest,yhat))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
          10       1.00      1.00      1.00         4
         100       0.00      0.00      0.00         0
          11       0.40      1.00      0.57         2
          12       1.00      1.00      1.00         2
          13       1.00      0.67      0.80         3
          14       0.50      0.50      0.50         2
          15       0.75      1.00      0.86         3
          16       1.00      1.00      1.00         4
          17       1.00      1.00      1.00         6
          18       0.50      0.67      0.57         3
          19       0.00      0.00      0.00         1
           2       0.50      1.00      0.67         2
          20       0.33      0.50      0.40         4
          21       0.67      1.00      0.80         2
          22       1.00      0.50      0.67         2
          23       0.60      0.75      0.67         4
          24       0.50      1.00      0.67         2
          25       1.00      1.00      1.00         2
          26       0.67      0.50      0.57         4
          27       0.60      0.75      0.67         4
          28       1.00      1.00      1.00         3
          29       1.00      1.00      1.00         5
           3       0.40      0.67      0.50         3
          30       0.50      1.00      0.67         1
          31       0.67      1.00      0.80         2
          32       0.83      1.00      0.91         5
          33       0.83      0.71      0.77         7
          34       0.43      1.00      0.60         3
          35       0.67      1.00      0.80         2
          36       1.00      0.50      0.67         2
          37       1.00      0.75      0.86         4
          38       0.57      1.00      0.73         4
          39       0.50      1.00      0.67         1
           4       1.00      0.20      0.33         5
          40       0.80      0.57      0.67         7
          41       0.50      0.33      0.40         6
          42       1.00      1.00      1.00         5
          43       0.00      0.00      0.00         0
          44       0.50      0.25      0.33         4
          45       0.50      0.50      0.50         2
          46       1.00      1.00      1.00         3
          47       1.00      0.60      0.75         5
          48       1.00      1.00      1.00         3
          49       0.00      0.00      0.00         1
           5       0.75      0.75      0.75         4
          50       0.00      0.00      0.00         3
          51       0.00      0.00      0.00         5
          52       0.50      0.20      0.29         5
          53       0.33      0.33      0.33         3
          54       0.33      0.33      0.33         3
          55       1.00      0.33      0.50         3
          56       0.83      1.00      0.91         5
          57       1.00      0.67      0.80         3
          58       1.00      0.67      0.80         3
          59       0.50      0.67      0.57         3
           6       0.40      1.00      0.57         2
          60       0.00      0.00      0.00         5
          61       0.50      0.33      0.40         3
          62       0.40      0.67      0.50         3
          63       0.00      0.00      0.00         1
          64       0.33      0.50      0.40         2
          65       1.00      1.00      1.00         4
          66       0.67      0.50      0.57         4
          67       0.33      0.33      0.33         3
          68       1.00      1.00      1.00         2
          69       0.50      0.50      0.50         2
           7       0.60      1.00      0.75         3
          70       0.00      0.00      0.00         3
          71       1.00      1.00      1.00         3
          72       0.50      1.00      0.67         1
          73       0.75      1.00      0.86         3
          74       0.33      0.50      0.40         2
          75       0.67      0.50      0.57         4
          76       1.00      0.25      0.40         4
          77       0.25      0.25      0.25         4
          78       0.50      0.25      0.33         4
          79       1.00      1.00      1.00         3
           8       1.00      1.00      1.00         3
          80       1.00      0.40      0.57         5
          81       0.67      0.50      0.57         4
          83       0.50      0.75      0.60         4
          84       0.50      1.00      0.67         3
          85       0.50      0.50      0.50         2
          86       0.22      0.50      0.31         4
          87       0.50      0.17      0.25         6
          88       1.00      1.00      1.00         1
          89       0.00      0.00      0.00         2
           9       1.00      0.80      0.89         5
          90       1.00      1.00      1.00         1
          91       1.00      0.67      0.80         6
          92       1.00      1.00      1.00         4
          93       0.67      0.67      0.67         3
          94       0.00      0.00      0.00         1
          95       1.00      1.00      1.00         3
          96       1.00      0.83      0.91         6
          97       0.67      1.00      0.80         2
          98       0.67      0.67      0.67         3
          99       0.60      0.43      0.50         7

    accuracy                           0.64       320
   macro avg       0.63      0.64      0.60       320
weighted avg       0.68      0.64      0.63       320

/home/pooya/.local/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/pooya/.local/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/pooya/.local/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/pooya/.local/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/pooya/.local/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/pooya/.local/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [ ]:
print(cr(ytrain,pipi.predisct(xtrain)))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        15
          10       1.00      1.00      1.00        12
         100       1.00      1.00      1.00        16
          11       1.00      1.00      1.00        14
          12       1.00      1.00      1.00        14
          13       1.00      1.00      1.00        13
          14       1.00      1.00      1.00        14
          15       1.00      1.00      1.00        13
          16       1.00      1.00      1.00        12
          17       1.00      1.00      1.00        10
          18       1.00      1.00      1.00        13
          19       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        14
          20       1.00      1.00      1.00        12
          21       1.00      1.00      1.00        14
          22       1.00      1.00      1.00        14
          23       1.00      1.00      1.00        12
          24       1.00      1.00      1.00        14
          25       1.00      1.00      1.00        14
          26       1.00      1.00      1.00        12
          27       1.00      1.00      1.00        12
          28       1.00      1.00      1.00        13
          29       1.00      1.00      1.00        11
           3       1.00      1.00      1.00        13
          30       1.00      1.00      1.00        15
          31       1.00      1.00      1.00        14
          32       1.00      1.00      1.00        11
          33       1.00      1.00      1.00         9
          34       1.00      1.00      1.00        13
          35       1.00      1.00      1.00        14
          36       1.00      1.00      1.00        14
          37       1.00      1.00      1.00        12
          38       1.00      1.00      1.00        12
          39       1.00      1.00      1.00        15
           4       1.00      1.00      1.00        11
          40       1.00      1.00      1.00         9
          41       1.00      1.00      1.00        10
          42       1.00      1.00      1.00        11
          43       1.00      1.00      1.00        16
          44       1.00      1.00      1.00        12
          45       1.00      1.00      1.00        14
          46       1.00      1.00      1.00        13
          47       1.00      1.00      1.00        11
          48       1.00      1.00      1.00        13
          49       1.00      1.00      1.00        15
           5       1.00      1.00      1.00        12
          50       1.00      1.00      1.00        13
          51       1.00      1.00      1.00        11
          52       1.00      1.00      1.00        11
          53       1.00      1.00      1.00        13
          54       1.00      1.00      1.00        13
          55       1.00      1.00      1.00        13
          56       1.00      1.00      1.00        11
          57       1.00      1.00      1.00        13
          58       1.00      1.00      1.00        13
          59       1.00      1.00      1.00        13
           6       1.00      1.00      1.00        14
          60       1.00      1.00      1.00        11
          61       1.00      1.00      1.00        13
          62       1.00      1.00      1.00        13
          63       1.00      1.00      1.00        15
          64       1.00      1.00      1.00        14
          65       1.00      1.00      1.00        12
          66       1.00      1.00      1.00        12
          67       1.00      1.00      1.00        13
          68       1.00      1.00      1.00        14
          69       1.00      1.00      1.00        14
           7       1.00      1.00      1.00        13
          70       1.00      1.00      1.00        13
          71       1.00      1.00      1.00        13
          72       1.00      1.00      1.00        15
          73       1.00      1.00      1.00        13
          74       1.00      1.00      1.00        14
          75       1.00      1.00      1.00        12
          76       1.00      1.00      1.00        12
          77       1.00      1.00      1.00        12
          78       1.00      1.00      1.00        12
          79       1.00      1.00      1.00        13
           8       1.00      1.00      1.00        13
          80       1.00      1.00      1.00        11
          81       1.00      1.00      1.00        12
          82       1.00      1.00      1.00        16
          83       1.00      1.00      1.00        12
          84       1.00      1.00      1.00        13
          85       1.00      1.00      1.00        14
          86       1.00      1.00      1.00        12
          87       1.00      1.00      1.00        10
          88       1.00      1.00      1.00        15
          89       1.00      1.00      1.00        14
           9       1.00      1.00      1.00        11
          90       1.00      1.00      1.00        15
          91       1.00      1.00      1.00        10
          92       1.00      1.00      1.00        12
          93       1.00      1.00      1.00        13
          94       1.00      1.00      1.00        15
          95       1.00      1.00      1.00        13
          96       1.00      1.00      1.00        10
          97       1.00      1.00      1.00        14
          98       1.00      1.00      1.00        13
          99       1.00      1.00      1.00         9

    accuracy                           1.00      1280
   macro avg       1.00      1.00      1.00      1280
weighted avg       1.00      1.00      1.00      1280